--plugins configuration needs to be on top
require("horn1347.plugins-setup")
require("horn1347.core.options")
require("horn1347.core.keymaps")
require("horn1347.core.colorscheme")
require("horn1347.plugins.nvim-tree")
require("horn1347.plugins.lualine")
require("horn1347.plugins.telescope")
require("horn1347.plugins.nvim-cmp")
require("horn1347.plugins.lsp.mason")
